# ------------------------------------------------------------------------------
# Support the Hero of Legend Quest!
# ------------------------------------------------------------------------------
github: [xopherdeep,knerd]
custom: ['https://www.buymeacoffee.com/youmeos']
