# ------------------------------------------------------------------------------
# Support the Hero of Legend Quest!
# ------------------------------------------------------------------------------
github: [knerd]
patreon: knerd
ko_fi: knerd
custom: ['https://www.buymeacoffee.com/knerd']
